import { movementId, nonEmptyString, positiveInt } from "./brand.ts";
import { yearSpan } from "./time.ts";
import { tokens, type DesignLanguage } from "./language.ts";
import {
  stillPattern,
  stillShape,
  stillWord,
  type SceneProgram,
} from "./scene.ts";
import { history, liveUrl, publication, work } from "./history.ts";
import { antiPattern, prompt, type Movement } from "./movement.ts";

function language(partial: DesignLanguage): DesignLanguage {
  return partial;
}

function program(partial: SceneProgram): SceneProgram {
  return partial;
}

export const web20: Movement = {
  id: movementId("web-2-0"),
  name: nonEmptyString("Web 2.0 gloss"),
  span: yearSpan(2004, 6),
  history: history(
    "Candy buttons, badges, reflections. The web as a product you log into.",
    "O'Reilly's Web 2.0 (2004) names the shift to software as a service and user-made content. Gmail, Flickr, Digg, Facebook, Twitter. AJAX. The look is specular: gradients, rounded rectangles, glass badges, reflected logos, a public beta sticker. 960-ish widths. Blue and orange. The page finally looks expensive in a way print designers recognized.",
  ),
  language: language({
    tokens: tokens({
      bg: "#dfe9f5",
      fg: "#1f2a38",
      accent: "#ff7a18",
      muted: "#4d5d73",
      border: "#8ab0d9",
      shadow: "#6ea3d9",
      fontDisplay: "Lucida Grande, Trebuchet MS, sans-serif",
      fontBody: "Lucida Grande, Tahoma, sans-serif",
      fontMono: "Monaco, monospace",
      radiusPx: 12,
      spacePx: 16,
    }),
    layout: {
      density: "regular",
      columns: 3,
      chrome: "dashboard",
      ornament: "gloss",
      nav: "top",
    },
    type: {
      displayScale: "medium",
      bodyMeasure: "readable",
      tracking: "tight",
      textCase: "as-written",
    },
    motion: {
      enter: "scale",
      durationMs: positiveInt(180),
      easing: "ease-out",
      loop: "none",
    },
  }),
  scene: program({
    geometry: {
      kind: "bevel-blocks",
      count: positiveInt(6),
      depth: positiveInt(3),
    },
    camera: { kind: "perspective", fov: positiveInt(40) },
    motion: { kind: "pulse", speed: positiveInt(3) },
    material: "accent",
    still: {
      alt: nonEmptyString("Glossy rounded rectangles and a beta badge."),
      marks: [
        stillShape("rectangle", "accent", 30, 40),
        stillWord("BETA", "fg", 72, 18),
      ],
    },
  }),
  antiPatterns: [
    antiPattern(
      "Flat fills",
      "Every button is a gradient with a specular ridge. Badges have a reflection. Corners are round.",
    ),
    antiPattern(
      "A static brochure",
      "This era is an application. Show a signed-in surface, a stream, or a compose box.",
    ),
  ],
  prompts: [
    prompt(
      "2006 startup",
      "Design a Web 2.0 product landing and app chrome. Lucida or Trebuchet, aqua blues, an orange call to action, glossy pill buttons, a beta badge, a 960px wrap, a tagline that could have been generated by a Web 2.0 name machine. Include an AJAX-feeling list, not a brochure.",
    ),
  ],
  works: [
    work({
      title: "Gmail",
      year: 2004,
      credit: "Google",
      ref: publication("Gmail launch", "Google", 2004),
    }),
    work({
      title: "Flickr",
      year: 2004,
      credit: "Ludicorp",
      ref: publication("Flickr", "Ludicorp / Yahoo", 2004),
    }),
    work({
      title: "What Is Web 2.0",
      year: 2005,
      credit: "Tim O'Reilly",
      ref: liveUrl("https://www.oreilly.com/pub/a/web2/archive/what-is-web-20.html"),
    }),
  ],
  answers: [movementId("standards")],
};

export const skeuomorphism: Movement = {
  id: movementId("skeuomorphism"),
  name: nonEmptyString("Skeuomorphism"),
  span: yearSpan(2007, 6),
  history: history(
    "Software as a physical object. Leather, felt, yellow pads, wooden shelves.",
    "The iPhone (2007) and iOS 1 through 6 teach a new public how to touch glass by quoting the world. Find My Friends is leather. Game Center is felt. Notes is a legal pad. Apple's product pages and a wave of web apps follow. The textures help until the gestures are learned. Then they become noise. iOS 7 ends the argument at Apple. The web keeps a few shelves and stitches for a while after.",
  ),
  language: language({
    tokens: tokens({
      bg: "#c9b79a",
      fg: "#2a1c12",
      accent: "#8b1e1e",
      muted: "#5c4633",
      border: "#8a6a45",
      shadow: "#4a331f",
      fontDisplay: "Baskerville, Palatino, serif",
      fontBody: "Lucida Grande, Geneva, sans-serif",
      fontMono: "Menlo, monospace",
      radiusPx: 8,
      spacePx: 18,
    }),
    layout: {
      density: "regular",
      columns: 2,
      chrome: "os-window",
      ornament: "grain",
      nav: "bottom",
    },
    type: {
      displayScale: "medium",
      bodyMeasure: "narrow",
      tracking: "normal",
      textCase: "as-written",
    },
    motion: {
      enter: "slide",
      durationMs: positiveInt(320),
      easing: "spring",
      loop: "none",
    },
  }),
  scene: program({
    geometry: { kind: "paper-layers", layers: positiveInt(5) },
    camera: { kind: "hero-tilt", fov: positiveInt(38) },
    motion: { kind: "parallax", strength: positiveInt(8) },
    material: "bg",
    still: {
      alt: nonEmptyString("Stacked paper with stitched leather edges."),
      marks: [
        stillPattern("noise", "border"),
        stillShape("rectangle", "accent", 22, 30),
      ],
    },
  }),
  antiPatterns: [
    antiPattern(
      "Flat iconography",
      "Quote a material. Stitch it, shadow it, give it a light source. The control should look holdable.",
    ),
    antiPattern(
      "Texture without light",
      "A leather overlay dumped on a rectangle is not skeuomorphism. Build highlights, inner shadows, and a horizon.",
    ),
  ],
  prompts: [
    prompt(
      "iOS 5 web app",
      "Design a small web app that could have shipped next to iOS 5. Linen or leather background, skeuomorphic controls, serif display on a paper surface, realistic shadows, a physical metaphor for the main object. Not a parody. Make it feel useful on a finger.",
    ),
  ],
  works: [
    work({
      title: "iPhone",
      year: 2007,
      credit: "Apple",
      ref: publication("iPhone introduction", "Apple", 2007),
    }),
    work({
      title: "Find My Friends / Game Center language",
      year: 2011,
      credit: "Apple",
      ref: publication("iOS 5 software", "Apple", 2011),
    }),
    work({
      title: "Path",
      year: 2010,
      credit: "Path",
      ref: publication("Path app", "Path", 2010),
    }),
  ],
  answers: [movementId("web-2-0")],
};

export const responsive: Movement = {
  id: movementId("responsive"),
  name: nonEmptyString("Responsive"),
  span: yearSpan(2010, 5),
  history: history(
    "One site, many viewports. Fluid grids, flexible images, media queries.",
    "Ethan Marcotte names responsive web design in A List Apart in 2010. The Boston Globe (2011) is the first large newsroom to ship it. Bootstrap (2011) spreads a 12-column habit. Separate m-dot sites start to look like a concession. The hamburger is a compromise, not a style. The real design move is a layout that reflows without becoming a different product.",
  ),
  language: language({
    tokens: tokens({
      bg: "#f7f5f2",
      fg: "#222222",
      accent: "#0a7cff",
      muted: "#666666",
      border: "#dddddd",
      shadow: "#bdbdbd",
      fontDisplay: "Helvetica Neue, Helvetica, Arial, sans-serif",
      fontBody: "Georgia, serif",
      fontMono: "Menlo, monospace",
      radiusPx: 3,
      spacePx: 20,
    }),
    layout: {
      density: "regular",
      columns: 12,
      chrome: "minimal",
      ornament: "grid",
      nav: "top",
    },
    type: {
      displayScale: "large",
      bodyMeasure: "readable",
      tracking: "normal",
      textCase: "as-written",
    },
    motion: {
      enter: "slide",
      durationMs: positiveInt(200),
      easing: "ease-out",
      loop: "none",
    },
  }),
  scene: program({
    geometry: { kind: "wire-lattice", divisions: positiveInt(12) },
    camera: { kind: "ortho", zoom: positiveInt(5) },
    motion: { kind: "none" },
    material: "accent",
    still: {
      alt: nonEmptyString("A 12 column lattice shrinking toward a phone."),
      marks: [
        stillPattern("grid", "border"),
        stillShape("rectangle", "accent", 10, 20),
        stillShape("rectangle", "muted", 70, 20),
      ],
    },
  }),
  antiPatterns: [
    antiPattern(
      "A separate mobile site",
      "One codebase. Media queries, fluid images, a grid that collapses. Do not fork m.example.com.",
    ),
    antiPattern(
      "Desktop-only hover as the only affordance",
      "If a task cannot be finished with a thumb, it is not responsive yet.",
    ),
  ],
  prompts: [
    prompt(
      "2011 news site",
      "Design a news homepage that works at 320, 768, and 1280 without hiding stories. Fluid grid, flexible images, a collapsing nav, serif body, sans UI. Quote Marcotte: the layout is a module that reflows, not a set of three mockups.",
    ),
  ],
  works: [
    work({
      title: "Responsive Web Design",
      year: 2010,
      credit: "Ethan Marcotte",
      ref: liveUrl("https://alistapart.com/article/responsive-web-design/"),
    }),
    work({
      title: "The Boston Globe",
      year: 2011,
      credit: "Upstatement / Filament Group / Boston Globe",
      ref: publication("Boston Globe responsive redesign", "The Boston Globe", 2011),
    }),
    work({
      title: "Bootstrap",
      year: 2011,
      credit: "Mark Otto / Jacob Thornton",
      ref: liveUrl("https://getbootstrap.com"),
    }),
  ],
  answers: [movementId("web-2-0"), movementId("standards")],
};

export const flat: Movement = {
  id: movementId("flat"),
  name: nonEmptyString("Flat design"),
  span: yearSpan(2012, 5),
  history: history(
    "Texture stripped. Bright fills, thin sans, icons without bevels.",
    "Windows 8 Metro (2012) and iOS 7 (2013) throw out the stitched world. Medium and a generation of startups go color fields, hairline type, and glyphs. Affordances get thinner. Screen density and performance are the excuse. Plenty of air. Plenty of confusion about what is tappable. The web copies Apple's marketing site more than Metro, then copies itself.",
  ),
  language: language({
    tokens: tokens({
      bg: "#ffffff",
      fg: "#111111",
      accent: "#007aff",
      muted: "#8e8e93",
      border: "#e5e5ea",
      shadow: "#d1d1d6",
      fontDisplay: "Helvetica Neue, Helvetica, Arial, sans-serif",
      fontBody: "Helvetica Neue, Helvetica, Arial, sans-serif",
      fontMono: "SF Mono, Menlo, monospace",
      radiusPx: 4,
      spacePx: 24,
    }),
    layout: {
      density: "sparse",
      columns: 1,
      chrome: "minimal",
      ornament: "none",
      nav: "top",
    },
    type: {
      displayScale: "billboard",
      bodyMeasure: "narrow",
      tracking: "tight",
      textCase: "as-written",
    },
    motion: {
      enter: "fade",
      durationMs: positiveInt(220),
      easing: "ease-out",
      loop: "none",
    },
  }),
  scene: program({
    geometry: { kind: "elevation-cards", count: positiveInt(3) },
    camera: { kind: "ortho", zoom: positiveInt(6) },
    motion: { kind: "none" },
    material: "accent",
    still: {
      alt: nonEmptyString("A white field and one blue glyph."),
      marks: [
        stillWord("Aa", "fg", 18, 42),
        stillShape("circle", "accent", 70, 42),
      ],
    },
  }),
  antiPatterns: [
    antiPattern(
      "Drop shadows as decoration",
      "If you need depth, use space and type scale, not a photo-texture or a skeuomorphic ledge.",
    ),
    antiPattern(
      "Mystery meat",
      "Flat is not an excuse to hide buttons. Contrast and hit area still have to work.",
    ),
  ],
  prompts: [
    prompt(
      "iOS 7 marketing page",
      "Design a 2013 product page. White field, one accent (iOS blue), Helvetica Neue Ultralight energy, huge type, no textures, no gradients except a simple fill, icons as line glyphs. Lots of leftover space. It should feel like a phone OS escaped onto the web.",
    ),
  ],
  works: [
    work({
      title: "Windows 8 Metro",
      year: 2012,
      credit: "Microsoft",
      ref: publication("Windows 8 design language", "Microsoft", 2012),
    }),
    work({
      title: "iOS 7",
      year: 2013,
      credit: "Apple",
      ref: publication("iOS 7", "Apple", 2013),
    }),
    work({
      title: "Medium",
      year: 2012,
      credit: "Evan Williams / Medium",
      ref: liveUrl("https://medium.com"),
    }),
  ],
  answers: [movementId("skeuomorphism"), movementId("responsive")],
};
